service: rust-lambda
frameworkVersion: "3"
configValidationMode: "warn"

provider:
  name: aws
  runtime: provided.al2023
  stage: dev
  region: us-west-1

package:
 individually: true

custom:
  rust:
    cargoLambda:
      docker: false

plugins:
  - serverless-rust-plugin

functions:
  get:
    handler: rust-lambda
    events:
      - http:
          path: get/{name}
          method: get